far_planner:
  ros__parameters:
    # Dynamic Planner Default Params
    main_run_freq: 2.5 # [Hz] How often the *planner* runs (replan rate).
    voxel_dim: 0.15  # Unit: meter. Smaller → sharper obstacle detail but heavier CPU/memory.
    robot_dim: 0.4   # Unit: meter. Collision *inflation radius* (effective robot “circle”) used for planning.
    vehicle_height: 0.3  # Unit: meter. Height of the robot base/sensor above ground used in terrain checks.
    sensor_range: 30.0  # Unit: meter. Max range of points used from the depth/LiDAR stream for mapping/planning.
    terrain_range: 15.0  # Unit: meter. Radius around the robot within which terrain analysis/costs are computed/maintained.
    local_planner_range: 5.0   # Unit: meter. Look-ahead radius/window for the local planner’s search.
    visualize_ratio: 0.75
    is_viewpoint_extend: true
    is_multi_layer: false
    is_opencv_visual: false # Obstacle Image Display
    is_static_env: true
    is_pub_boundary: false
    is_debug_output: false
    is_attempt_autoswitch: true  # Auto switch to attemptable navigation
    world_frame: map

    # Graph Messager
    graph_msger/robot_id: 1  # graph from robot id "0" is extracted from files

    # Map Handler Params
    map_handler/floor_height: 1.0     # Unit: meter
    map_handler/cell_length: 5.0     # Unit: meter
    map_handler/map_grid_max_length: 1000.0   # Unit: meter
    map_handler/map_grad_max_height: 100.0   # Unit: meter

    # Dynamic Planner Utility Params
    util/angle_noise: 15.0 # Unit: degree
    util/accept_max_align_angle: 4.0  # Unit: degree
    util/obs_inflate_size: 1
    util/new_intensity_thred: 2.0
    util/terrain_free_Z: 0.2
    util/dyosb_update_thred: 4
    util/new_point_counter: 5
    util/dynamic_obs_dacay_time: 10.0 # Unit: second
    util/new_points_decay_time: 1.0  # Unit: second

    # Dynamic Graph Params
    graph/connect_votes_size: 10
    graph/clear_dumper_thred: 4
    graph/node_finalize_thred: 6
    graph/filter_pool_size: 12

    # Corner Detector Params
    c_detector/resize_ratio: 3.0
    c_detector/filter_count_value: 3
    c_detector/is_save_img: false
    c_detector/img_folder_path: /path

    # Graph Planner Params
    g_planner/converge_distance: 0.5  # Unit: meter
    g_planner/goal_adjust_radius: 2.0  # Unit: meter
    g_planner/free_counter_thred: 7
    g_planner/reach_goal_vote_size: 3
    g_planner/path_momentum_thred: 3
